apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: dev
          hostPath:
            path: /home/root/code/free-certs-for-everyone
      containers:
      - name: {{ .Chart.Name }}
        image: "node:6"
        imagePullPolicy: Always
        env:
          - name: DOMAIN
            value: {{ .Values.domain }}
        command:
          - bash
          - -c
          - cd /home/root/code/free-certs-for-everyone && npm start
        ports:
        - containerPort: 8989
        volumeMounts:
          - name: dev
            mountPath: /home/root/code/free-certs-for-everyone
