
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-http
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  rules:
  - host: "*.{{ .Values.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
